version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: answerdb
      POSTGRES_USER: answeruser
      POSTGRES_PASSWORD: answerpass
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: apache/answer-backend:latest
    depends_on:
      - db
    ports:
      - "9090:9090"
    environment:
      ANSWER_DB_HOST: db
      ANSWER_DB_PORT: 5432
      ANSWER_DB_NAME: answerdb
      ANSWER_DB_USER: answeruser
      ANSWER_DB_PASSWORD: answerpass

  frontend:
    image: apache/answer-frontend:latest
    depends_on:
      - backend
    ports:
      - "9080:80"

volumes:
  pgdata:
